### ISSUE TITLE
Federated Subscriptions are now supported in GraphOS!

### ISSUE THREAD

**Issue by smyrick** [sammysaglam/federation-with-subscriptions#20]
Federated Subscriptions are now supported in GraphOS!

Community libraries like this helped many implement their graphs they wanted and we are grateful for the extensions. Federation now supports subscriptions with out the need for any wrappers

https://www.apollographql.com/blog/announcement/backend/federated-subscriptions-in-graphos-real-time-data-at-scale/

**Comment by sammysaglam** [comment]
thanks for the update @smyrick ! ill find some time to add a deprecation notice to this project 🎉
